// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCB14nzyLm7EwEwGo6-ZQiIoW0GUjiRrAw',
    appId: '1:771732170560:web:013fec3f13e25556aefca5',
    messagingSenderId: '771732170560',
    projectId: 'tiklogistics-637e9',
    authDomain: 'tiklogistics-637e9.firebaseapp.com',
    storageBucket: 'tiklogistics-637e9.appspot.com',
    measurementId: 'G-5N5GT4Y2FX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDijpcFM5l6d8TkJc9ttPAHWLlOJBlxVYI',
    appId: '1:771732170560:android:134415933927e623aefca5',
    messagingSenderId: '771732170560',
    projectId: 'tiklogistics-637e9',
    storageBucket: 'tiklogistics-637e9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGxpM89PPE1CTRcnOnzI06C1E7kWsO0-w',
    appId: '1:771732170560:ios:64135ee98f9fa79faefca5',
    messagingSenderId: '771732170560',
    projectId: 'tiklogistics-637e9',
    storageBucket: 'tiklogistics-637e9.appspot.com',
    androidClientId: '771732170560-fj4s75ak9amqpelvjan0l6lhpanilf16.apps.googleusercontent.com',
    iosClientId: '771732170560-om3bef4l6mbvk5lmneo2ukmdiskst4oh.apps.googleusercontent.com',
    iosBundleId: 'com.example.tiklogistics',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGxpM89PPE1CTRcnOnzI06C1E7kWsO0-w',
    appId: '1:771732170560:ios:64135ee98f9fa79faefca5',
    messagingSenderId: '771732170560',
    projectId: 'tiklogistics-637e9',
    storageBucket: 'tiklogistics-637e9.appspot.com',
    androidClientId: '771732170560-fj4s75ak9amqpelvjan0l6lhpanilf16.apps.googleusercontent.com',
    iosClientId: '771732170560-om3bef4l6mbvk5lmneo2ukmdiskst4oh.apps.googleusercontent.com',
    iosBundleId: 'com.example.tiklogistics',
  );
}
